version: '3'
services:
  exemplar_dev:
    image: flavioespinoza/drone-react-build:latest
    container_name: exemplar_dev
    command: yarn start-dev
    volumes:
      - .:/wsdev/authnet-app/
      - /wsdev/authnet-app/node_modules
    ports:
      - "8080:8080"
    environment:
      PORT: "5000"
      NODE_ENV: "development"
      DOMAIN_ENV: "not_pd"